on: 
  push:
    branches:
    - master
jobs:
  test:
    name: npm install, build and test (vitest)
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm test
    
